"""initial_schema

Revision ID: 5baeca04aab3
Revises:
Create Date: 2026-06-02 19:25:49.267642
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# Use PostgreSQL's efficient JSONB where available, while retaining support for
# the zero-config SQLite development database.
JSON_TYPE = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")

# revision identifiers
revision: str = '5baeca04aab3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('image_name', sa.String(length=512), nullable=False),
    sa.Column('categories', JSON_TYPE, nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('filter_mode', sa.String(length=16), nullable=True),
    sa.Column('filter_nms_iou', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_created_at', 'detections', ['created_at'], unique=False)
    op.create_index('ix_detections_status', 'detections', ['status'], unique=False)
    op.create_table('training_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_variant', sa.String(length=32), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('imgsz', sa.Integer(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.Column('class_map', JSON_TYPE, nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics', JSON_TYPE, nullable=True),
    sa.Column('model_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_jobs_status', 'training_jobs', ['status'], unique=False)
    op.create_table('detection_boxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=256), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=False),
    sa.Column('y1', sa.Integer(), nullable=False),
    sa.Column('x2', sa.Integer(), nullable=False),
    sa.Column('y2', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detection_boxes_detection_id', 'detection_boxes', ['detection_id'], unique=False)
    op.create_table('training_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_job_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_detections_detection_id', 'training_detections', ['detection_id'], unique=False)
    op.create_index('ix_training_detections_job_id', 'training_detections', ['training_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_detections_job_id', table_name='training_detections')
    op.drop_index('ix_training_detections_detection_id', table_name='training_detections')
    op.drop_table('training_detections')
    op.drop_index('ix_detection_boxes_detection_id', table_name='detection_boxes')
    op.drop_table('detection_boxes')
    op.drop_index('ix_training_jobs_status', table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index('ix_detections_status', table_name='detections')
    op.drop_index('ix_detections_created_at', table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
